import { createContext, useContext, useState } from "react";

export type Lang = "ES" | "EN" | "DE" | "FR";

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "ES",
  setLang: () => {},
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    return (localStorage.getItem("lang") as Lang) || "ES";
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("lang", l);
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

export function localizedText(
  es: string | null | undefined,
  en: string | null | undefined,
  de: string | null | undefined,
  lang: Lang,
  fr?: string | null | undefined
): string {
  if (lang === "EN" && en) return en;
  if (lang === "DE" && de) return de;
  if (lang === "FR" && fr) return fr;
  return es || "";
}

type TS = { ES: string; EN: string; DE: string; FR: string };

export const T = {
  nav: {
    home:            { ES: "Inicio",           EN: "Home",            DE: "Startseite",          FR: "Accueil" } as TS,
    razonDeSer:      { ES: "Razón de ser",     EN: "Our Mission",     DE: "Unsere Mission",       FR: "Notre Mission" } as TS,
    apadrinamiento:  { ES: "Apadrinamiento",   EN: "Sponsorship",     DE: "Patenschaft",          FR: "Parrainage" } as TS,
    news:            { ES: "Noticias",         EN: "News",            DE: "Nachrichten",          FR: "Actualités" } as TS,
    activities:      { ES: "Actividades",      EN: "Activities",      DE: "Aktivitäten",          FR: "Activités" } as TS,
    store:           { ES: "Tienda",           EN: "Store",           DE: "Shop",                 FR: "Boutique" } as TS,
    contact:         { ES: "Contacto",         EN: "Contact",         DE: "Kontakt",              FR: "Contact" } as TS,
    access:          { ES: "Acceder",          EN: "Sign in",         DE: "Anmelden",             FR: "Se connecter" } as TS,
    myPanel:         { ES: "Mi panel de socio",EN: "My member panel", DE: "Mein Mitgliederbereich",FR: "Mon espace membre" } as TS,
    adminPanel:      { ES: "Panel Admin",      EN: "Admin Panel",     DE: "Admin-Panel",          FR: "Panneau Admin" } as TS,
    logout:          { ES: "Cerrar sesión",    EN: "Log out",         DE: "Abmelden",             FR: "Se déconnecter" } as TS,
    search:          { ES: "Buscar...",        EN: "Search...",       DE: "Suchen...",            FR: "Rechercher..." } as TS,
    cart:            { ES: "Carrito",          EN: "Cart",            DE: "Warenkorb",            FR: "Panier" } as TS,
    sessionClosed:   { ES: "Sesión cerrada",   EN: "Session closed",  DE: "Sitzung beendet",      FR: "Session fermée" } as TS,
    sessionClosedDesc:{ ES: "Has cerrado sesión correctamente.", EN: "You have logged out successfully.", DE: "Du hast dich erfolgreich abgemeldet.", FR: "Vous avez été déconnecté avec succès." } as TS,
  },
  footer: {
    tagline:      { ES: "Construyendo un futuro lleno de esperanza y oportunidades para quienes más lo necesitan. Tu apoyo marca la diferencia.", EN: "Building a future full of hope and opportunities for those who need it most. Your support makes a difference.", DE: "Eine Zukunft voller Hoffnung und Chancen für die Bedürftigsten aufbauen. Deine Unterstützung macht den Unterschied.", FR: "Construire un avenir plein d'espoir et d'opportunités pour ceux qui en ont le plus besoin. Votre soutien fait la différence." } as TS,
    contactTitle: { ES: "Contacto",             EN: "Contact",              DE: "Kontakt",                    FR: "Contact" } as TS,
    legalTitle:   { ES: "Información Legal",    EN: "Legal Information",    DE: "Rechtliche Informationen",   FR: "Informations Légales" } as TS,
    legalNotice:  { ES: "Aviso Legal",          EN: "Legal Notice",         DE: "Impressum",                  FR: "Mentions Légales" } as TS,
    privacy:      { ES: "Política de Privacidad",EN: "Privacy Policy",      DE: "Datenschutzrichtlinie",      FR: "Politique de Confidentialité" } as TS,
    cookies:      { ES: "Política de Cookies",  EN: "Cookie Policy",        DE: "Cookie-Richtlinie",          FR: "Politique de Cookies" } as TS,
    contactUs:    { ES: "Contactar",            EN: "Contact us",           DE: "Kontakt aufnehmen",          FR: "Nous contacter" } as TS,
    rights:       { ES: "Todos los derechos reservados.", EN: "All rights reserved.", DE: "Alle Rechte vorbehalten.", FR: "Tous droits réservés." } as TS,
    devBy:        { ES: "Desarrollado por",     EN: "Developed by",         DE: "Entwickelt von",             FR: "Développé par" } as TS,
  },
  home: {
    badge:             { ES: "Juntos cambiamos vidas",          EN: "Together we change lives",         DE: "Gemeinsam verändern wir Leben",           FR: "Ensemble nous changeons des vies" } as TS,
    heroTitle1:        { ES: "Pequeños gestos,",                EN: "Small gestures,",                  DE: "Kleine Gesten,",                          FR: "Petits gestes," } as TS,
    heroTitle2:        { ES: "grandes sonrisas.",               EN: "great smiles.",                    DE: "große Lächeln.",                           FR: "grands sourires." } as TS,
    heroDesc:          { ES: "Trabajamos cada día para construir un futuro lleno de oportunidades, amor y esperanza para quienes más lo necesitan.", EN: "We work every day to build a future full of opportunities, love and hope for those who need it most.", DE: "Wir arbeiten täglich daran, eine Zukunft voller Chancen, Liebe und Hoffnung für die Bedürftigsten zu gestalten.", FR: "Nous travaillons chaque jour pour construire un avenir plein d'opportunités, d'amour et d'espoir pour ceux qui en ont le plus besoin." } as TS,
    collaborate:       { ES: "Colabora hoy",                   EN: "Collaborate today",                DE: "Jetzt mitmachen",                         FR: "Collaborer aujourd'hui" } as TS,
    learnAboutUs:      { ES: "Conócenos",                      EN: "Learn about us",                   DE: "Über uns",                                FR: "Qui sommes-nous" } as TS,
    commitment:        { ES: "Compromiso",                     EN: "Commitment",                       DE: "Engagement",                              FR: "Engagement" } as TS,
    commitmentDesc:    { ES: "Dedicación total al bienestar y desarrollo integral de cada niño.", EN: "Total dedication to the well-being and integral development of each child.", DE: "Vollständiges Engagement für das Wohlergehen jedes Kindes.", FR: "Dévouement total au bien-être et au développement intégral de chaque enfant." } as TS,
    community:         { ES: "Comunidad",                      EN: "Community",                        DE: "Gemeinschaft",                            FR: "Communauté" } as TS,
    communityDesc:     { ES: "Creamos lazos fuertes entre familias, voluntarios y padrinos.", EN: "We create strong bonds between families, volunteers and sponsors.", DE: "Wir schaffen starke Verbindungen zwischen Familien, Freiwilligen und Paten.", FR: "Nous créons des liens forts entre les familles, les bénévoles et les parrains." } as TS,
    transparency:      { ES: "Transparencia",                  EN: "Transparency",                     DE: "Transparenz",                             FR: "Transparence" } as TS,
    transparencyDesc:  { ES: "Claridad total en la gestión de recursos y el impacto generado.", EN: "Total clarity in resource management and the impact generated.", DE: "Volle Klarheit bei der Ressourcenverwaltung und den Auswirkungen.", FR: "Transparence totale dans la gestion des ressources et l'impact généré." } as TS,
    upcomingActivities:{ ES: "Próximas Actividades",           EN: "Upcoming Activities",              DE: "Kommende Aktivitäten",                    FR: "Prochaines Activités" } as TS,
    activitiesSubDesc: { ES: "Participa en nuestros eventos y forma parte de la comunidad.", EN: "Join our events and be part of the community.", DE: "Nimm an unseren Veranstaltungen teil und werde Teil der Gemeinschaft.", FR: "Participez à nos événements et faites partie de la communauté." } as TS,
    seeAll:            { ES: "Ver todas",                      EN: "See all",                          DE: "Alle anzeigen",                           FR: "Voir tout" } as TS,
    comingSoon:        { ES: "Próximamente nuevas actividades",EN: "New activities coming soon",        DE: "Bald neue Aktivitäten",                   FR: "Nouvelles activités bientôt" } as TS,
    latestNews:        { ES: "Últimas Noticias",               EN: "Latest News",                      DE: "Neueste Nachrichten",                     FR: "Dernières Actualités" } as TS,
    newsSubDesc:       { ES: "Mantente al día de nuestras acciones y logros.", EN: "Stay up to date with our actions and achievements.", DE: "Bleibe über unsere Aktivitäten auf dem Laufenden.", FR: "Restez informé de nos actions et réalisations." } as TS,
    solidarityStore:   { ES: "Tienda Solidaria",               EN: "Solidarity Store",                 DE: "Solidaritätsladen",                       FR: "Boutique Solidaire" } as TS,
    storeDesc:         { ES: "Compra con propósito. Cada artículo ayuda a financiar nuestros proyectos.", EN: "Shop with purpose. Every item helps fund our projects.", DE: "Kaufe mit Sinn. Jeder Artikel hilft, unsere Projekte zu finanzieren.", FR: "Achetez avec un but. Chaque article aide à financer nos projets." } as TS,
    seeStore:          { ES: "Ver tienda",                     EN: "See store",                        DE: "Shop ansehen",                            FR: "Voir la boutique" } as TS,
    comingSoonStore:   { ES: "Próximamente artículos en la tienda", EN: "Store items coming soon",      DE: "Bald Artikel im Shop",                    FR: "Articles bientôt disponibles" } as TS,
    ctaTitle:          { ES: "¿Quieres ser parte del cambio?", EN: "Do you want to be part of the change?", DE: "Möchtest du Teil des Wandels sein?",    FR: "Voulez-vous faire partie du changement ?" } as TS,
    ctaDesc:           { ES: "Tu apoyo hace posible que sigamos creando historias con final feliz. Descubre cómo puedes colaborar.", EN: "Your support makes it possible for us to keep creating stories with happy endings. Find out how you can help.", DE: "Deine Unterstützung ermöglicht es uns, weiterhin Geschichten mit glücklichem Ende zu schaffen.", FR: "Votre soutien nous permet de continuer à créer des histoires à heureux dénouement. Découvrez comment collaborer." } as TS,
    ctaBtn:            { ES: "Contáctanos ahora",              EN: "Contact us now",                   DE: "Kontaktiere uns jetzt",                   FR: "Contactez-nous maintenant" } as TS,
    seeAllActivities:  { ES: "Ver todas las actividades",      EN: "See all activities",               DE: "Alle Aktivitäten ansehen",                FR: "Voir toutes les activités" } as TS,
    seeAllNewsBtn:     { ES: "Ver todas las noticias",         EN: "See all news",                     DE: "Alle Nachrichten ansehen",                FR: "Voir toutes les actualités" } as TS,
    seeAllStore:       { ES: "Ver toda la tienda",             EN: "See full store",                   DE: "Gesamten Shop ansehen",                   FR: "Voir toute la boutique" } as TS,
  },
  activities: {
    pageTitle: { ES: "Un Recorrido por Nuestra Historia", EN: "A Journey Through Our History", DE: "Eine Reise durch unsere Geschichte", FR: "Un Parcours à Travers Notre Histoire" } as TS,
    pageDesc:  { ES: "A lo largo de los años, impulsados desde la Dirección del Colegio madrileño JOYFE, hemos realizado infinidad de acciones de sensibilización con todo tipo de fines.", EN: "Over the years, driven by the leadership of the Madrid school JOYFE, we have carried out countless awareness actions for all kinds of purposes.", DE: "Im Laufe der Jahre haben wir unzählige Sensibilisierungsaktionen für alle Arten von Zwecken durchgeführt.", FR: "Au fil des années, nous avons réalisé d'innombrables actions de sensibilisation pour toutes sortes de causes." } as TS,
    noActivities: { ES: "No hay actividades programadas próximamente.", EN: "No activities scheduled soon.", DE: "Keine Aktivitäten demnächst geplant.", FR: "Pas d'activités programmées prochainement." } as TS,
  },
  news: {
    pageTitle: { ES: "Noticias y Actualidad",  EN: "News & Updates",       DE: "Neuigkeiten & Aktuelles",   FR: "Actualités & Nouvelles" } as TS,
    pageDesc:  { ES: "Descubre nuestras últimas historias, logros y novedades. Transparencia y cercanía en cada paso que damos.", EN: "Discover our latest stories, achievements and news. Transparency and closeness in every step we take.", DE: "Entdecke unsere neuesten Geschichten und Neuigkeiten. Transparenz bei jedem Schritt.", FR: "Découvrez nos dernières histoires, réalisations et actualités. Transparence à chaque étape." } as TS,
    noNews:    { ES: "No hay noticias disponibles en este momento.", EN: "No news available at the moment.", DE: "Derzeit keine Nachrichten verfügbar.", FR: "Aucune actualité disponible pour le moment." } as TS,
  },
  store: {
    badge:          { ES: "Tienda Solidaria",         EN: "Solidarity Store",       DE: "Solidaritätsladen",        FR: "Boutique Solidaire" } as TS,
    title:          { ES: "Compra con propósito",     EN: "Shop with purpose",      DE: "Sinnvoll einkaufen",       FR: "Achetez avec un but" } as TS,
    desc:           { ES: "Cada compra contribuye directamente a nuestros proyectos educativos y solidarios.", EN: "Every purchase directly contributes to our educational and solidarity projects.", DE: "Jeder Kauf trägt direkt zu unseren Projekten bei.", FR: "Chaque achat contribue directement à nos projets éducatifs et solidaires." } as TS,
    searchPlaceholder:{ ES: "Buscar productos...",    EN: "Search products...",     DE: "Produkte suchen...",       FR: "Rechercher des produits..." } as TS,
    all:            { ES: "Todos",                    EN: "All",                    DE: "Alle",                     FR: "Tous" } as TS,
    outOfStock:     { ES: "Agotado",                  EN: "Out of stock",           DE: "Ausverkauft",              FR: "Épuisé" } as TS,
    addToCart:      { ES: "Añadir",                   EN: "Add",                    DE: "Hinzufügen",               FR: "Ajouter" } as TS,
    noProducts:     { ES: "No se encontraron productos", EN: "No products found",   DE: "Keine Produkte gefunden",  FR: "Aucun produit trouvé" } as TS,
    addedToCart:    { ES: "Añadido al carrito",       EN: "Added to cart",          DE: "Zum Warenkorb hinzugefügt",FR: "Ajouté au panier" } as TS,
  },
  contact: {
    pageTitle:        { ES: "Estamos aquí para ti",         EN: "We are here for you",          DE: "Wir sind für dich da",               FR: "Nous sommes là pour vous" } as TS,
    pageDesc:         { ES: "¿Tienes preguntas, ideas o quieres colaborar? Escríbenos, nos encantará escucharte.", EN: "Do you have questions, ideas or want to collaborate? Write to us, we will be happy to hear from you.", DE: "Hast du Fragen oder möchtest du mitarbeiten? Schreib uns!", FR: "Vous avez des questions ou souhaitez collaborer ? Écrivez-nous !" } as TS,
    infoTitle:        { ES: "Información de contacto",     EN: "Contact information",           DE: "Kontaktinformationen",               FR: "Informations de contact" } as TS,
    email:            { ES: "Email",                       EN: "Email",                         DE: "E-Mail",                             FR: "E-mail" } as TS,
    phone:            { ES: "Teléfono",                    EN: "Phone",                         DE: "Telefon",                            FR: "Téléphone" } as TS,
    address:          { ES: "Dirección",                   EN: "Address",                       DE: "Adresse",                            FR: "Adresse" } as TS,
    hours:            { ES: "Horario de atención",         EN: "Office hours",                  DE: "Öffnungszeiten",                     FR: "Horaires d'ouverture" } as TS,
    hoursValue:       { ES: "Lunes a Viernes: 9:00 – 17:00", EN: "Monday to Friday: 9:00 – 17:00", DE: "Mo–Fr: 9:00 – 17:00",            FR: "Lun–Ven : 9h00 – 17h00" } as TS,
    formTitle:        { ES: "Envíanos un mensaje",         EN: "Send us a message",             DE: "Schick uns eine Nachricht",          FR: "Envoyez-nous un message" } as TS,
    formDesc:         { ES: "Completa el formulario y te contactaremos.", EN: "Fill out the form and we will contact you.", DE: "Füll das Formular aus und wir melden uns.", FR: "Remplissez le formulaire et nous vous contacterons." } as TS,
    name:             { ES: "Nombre completo",             EN: "Full name",                     DE: "Vollständiger Name",                 FR: "Nom complet" } as TS,
    namePlaceholder:  { ES: "Tu nombre",                   EN: "Your name",                     DE: "Dein Name",                          FR: "Votre nom" } as TS,
    emailLabel:       { ES: "Correo electrónico",          EN: "Email address",                 DE: "E-Mail-Adresse",                     FR: "Adresse e-mail" } as TS,
    message:          { ES: "Mensaje",                     EN: "Message",                       DE: "Nachricht",                          FR: "Message" } as TS,
    messagePlaceholder:{ ES: "¿En qué podemos ayudarte?", EN: "How can we help you?",           DE: "Wie können wir dir helfen?",         FR: "Comment pouvons-nous vous aider ?" } as TS,
    send:             { ES: "Enviar Mensaje",              EN: "Send Message",                  DE: "Nachricht senden",                   FR: "Envoyer le Message" } as TS,
    sending:          { ES: "Enviando...",                 EN: "Sending...",                    DE: "Senden...",                          FR: "Envoi en cours..." } as TS,
    successTitle:     { ES: "¡Mensaje enviado!",           EN: "Message sent!",                 DE: "Nachricht gesendet!",                FR: "Message envoyé !" } as TS,
    successDesc:      { ES: "Gracias por contactarnos. Te responderemos lo antes posible.", EN: "Thank you for contacting us. We will respond as soon as possible.", DE: "Danke! Wir antworten so bald wie möglich.", FR: "Merci de nous avoir contactés. Nous vous répondrons dès que possible." } as TS,
    errorTitle:       { ES: "Error al enviar",             EN: "Error sending",                 DE: "Fehler beim Senden",                 FR: "Erreur d'envoi" } as TS,
  },
  auth: {
    welcome:           { ES: "¡Bienvenido!",              EN: "Welcome!",                DE: "Willkommen!",                  FR: "Bienvenue !" } as TS,
    loginSuccess:      { ES: "Has iniciado sesión correctamente.", EN: "You have successfully logged in.", DE: "Du hast dich erfolgreich angemeldet.", FR: "Vous êtes connecté avec succès." } as TS,
    accountCreated:    { ES: "¡Cuenta creada!",           EN: "Account created!",        DE: "Konto erstellt!",              FR: "Compte créé !" } as TS,
    registerSuccess:   { ES: "Te has registrado correctamente.", EN: "You have registered successfully.", DE: "Du hast dich erfolgreich registriert.", FR: "Vous vous êtes inscrit avec succès." } as TS,
    loginTitle:        { ES: "Iniciar Sesión",            EN: "Sign In",                 DE: "Anmelden",                     FR: "Se connecter" } as TS,
    registerTitle:     { ES: "Crear Cuenta",              EN: "Create Account",          DE: "Konto erstellen",              FR: "Créer un compte" } as TS,
    loginSubtitle:     { ES: "Accede a tu espacio de socio", EN: "Access your member space", DE: "Zugang zu deinem Mitgliederbereich", FR: "Accédez à votre espace membre" } as TS,
    registerSubtitle:  { ES: "Únete a la comunidad solidaria", EN: "Join the solidarity community", DE: "Trete der Solidaritätsgemeinschaft bei", FR: "Rejoignez la communauté solidaire" } as TS,
    email:             { ES: "Email",                     EN: "Email",                   DE: "E-Mail",                       FR: "E-mail" } as TS,
    password:          { ES: "Contraseña",                EN: "Password",                DE: "Passwort",                     FR: "Mot de passe" } as TS,
    username:          { ES: "Nombre de usuario",         EN: "Username",                DE: "Benutzername",                 FR: "Nom d'utilisateur" } as TS,
    loginBtn:          { ES: "Iniciar Sesión",            EN: "Sign In",                 DE: "Anmelden",                     FR: "Se connecter" } as TS,
    registerBtn:       { ES: "Crear Cuenta",              EN: "Create Account",          DE: "Konto erstellen",              FR: "Créer un compte" } as TS,
    loggingIn:         { ES: "Iniciando sesión...",       EN: "Signing in...",           DE: "Anmelden...",                  FR: "Connexion..." } as TS,
    registering:       { ES: "Creando cuenta...",         EN: "Creating account...",     DE: "Konto wird erstellt...",       FR: "Création du compte..." } as TS,
    haveAccount:       { ES: "¿Ya tienes cuenta?",        EN: "Already have an account?",DE: "Bereits ein Konto?",           FR: "Vous avez déjà un compte ?" } as TS,
    noAccount:         { ES: "¿No tienes cuenta?",        EN: "Don't have an account?",  DE: "Noch kein Konto?",             FR: "Pas encore de compte ?" } as TS,
    signIn:            { ES: "Inicia sesión",             EN: "Sign in",                 DE: "Anmelden",                     FR: "Se connecter" } as TS,
    signUp:            { ES: "Regístrate",                EN: "Sign up",                 DE: "Registrieren",                 FR: "S'inscrire" } as TS,
    privacyLabel:      { ES: "Acepto la",                 EN: "I accept the",            DE: "Ich akzeptiere die",           FR: "J'accepte la" } as TS,
    privacyLink:       { ES: "Política de Privacidad",    EN: "Privacy Policy",          DE: "Datenschutzrichtlinie",        FR: "Politique de confidentialité" } as TS,
    minChars3:         { ES: "Mínimo 3 caracteres",       EN: "At least 3 characters",   DE: "Mindestens 3 Zeichen",         FR: "Au moins 3 caractères" } as TS,
    minChars6:         { ES: "Mínimo 6 caracteres",       EN: "At least 6 characters",   DE: "Mindestens 6 Zeichen",         FR: "Au moins 6 caractères" } as TS,
    invalidEmail:      { ES: "Email inválido",            EN: "Invalid email",           DE: "Ungültige E-Mail",             FR: "E-mail invalide" } as TS,
    requiredPassword:  { ES: "Introduce tu contraseña",   EN: "Enter your password",     DE: "Bitte Passwort eingeben",      FR: "Entrez votre mot de passe" } as TS,
    acceptTerms:       { ES: "Debes aceptar la política de privacidad para registrarte", EN: "You must accept the privacy policy to register", DE: "Du musst die Datenschutzrichtlinie akzeptieren", FR: "Vous devez accepter la politique de confidentialité" } as TS,
  },
  razon: {
    headerTitle: { ES: "Alumnos Solidarios, Razón de Ser", EN: "Alumnos Solidarios, Reason for Being", DE: "Alumnos Solidarios, Sinn des Seins", FR: "Alumnos Solidarios, Raison d'Être" } as TS,
    headerDesc: { ES: "Nuestra historia, misión y el compromiso que nos impulsa cada día.", EN: "Our history, mission and the commitment that drives us every day.", DE: "Unsere Geschichte, Mission und das Engagement, das uns jeden Tag antreibt.", FR: "Notre histoire, mission et l'engagement qui nous anime chaque jour." } as TS,
    sec1p1: { ES: "Está asociación de Alumnos Solidarios nació con el objetivo de aunar la fuerza del conocimiento, adquirido en los años de formación académica, para impulsar el cambio social y económico a beneficio de sociedades y grupos menos favorecidos.", EN: "This association of Alumnos Solidarios was born with the goal of harnessing the power of knowledge, acquired during years of academic training, to drive social and economic change for the benefit of less favoured societies and groups.", DE: "Dieser Verein der Alumnos Solidarios wurde mit dem Ziel gegründet, die Kraft des Wissens, das in den Ausbildungsjahren erworben wurde, zu bündeln, um den sozialen und wirtschaftlichen Wandel zugunsten benachteiligter Gesellschaften und Gruppen voranzutreiben.", FR: "Cette association d'Alumnos Solidarios est née avec pour objectif de rassembler la force de la connaissance, acquise pendant les années de formation académique, afin de favoriser le changement social et économique au bénéfice des sociétés et groupes les moins favorisés." } as TS,
    sec1p2: { ES: "La mirada solidaria tiene el poder de transformar el mundo. Potenciada desde la infancia por los educadores, que son la familia y los maestros, y bien conducida a lo largo de los años de formación superior, se convierte en una vacuna frente a la indiferencia. Ser solidario es una actitud ante la vida, es querer dejar una huella positiva en este mundo de desigualdades, identificar la necesidad y concentrarse en la búsqueda de soluciones.", EN: "The solidarity gaze has the power to transform the world. Strengthened from childhood by educators — family and teachers — and well guided throughout the years of higher education, it becomes a vaccine against indifference. Being caring is an attitude towards life; it means wanting to leave a positive mark on this world of inequalities, identifying needs and focusing on finding solutions.", DE: "Der solidarische Blick hat die Kraft, die Welt zu verändern. Von Kindheit an durch Erzieher – Familie und Lehrer – gestärkt und in den Bildungsjahren gut gelenkt, wird er zum Schutz gegen Gleichgültigkeit. Solidarisch zu sein ist eine Lebenshaltung; es bedeutet, eine positive Spur in dieser ungleichen Welt hinterlassen zu wollen, Bedürfnisse zu erkennen und sich auf die Suche nach Lösungen zu konzentrieren.", FR: "Le regard solidaire a le pouvoir de transformer le monde. Renforcé dès l'enfance par les éducateurs — la famille et les enseignants — et bien orienté au fil des années de formation supérieure, il devient un vaccin contre l'indifférence. Être solidaire est une attitude face à la vie ; c'est vouloir laisser une empreinte positive dans ce monde d'inégalités, identifier les besoins et se concentrer sur la recherche de solutions." } as TS,
    sec1p3: { ES: "Una persona solidaria no pasa por la vida con una venda de quita y pon, a conveniencia. Además, tiene en sus genes adquiridos el poder de mover conciencias y sumar al propósito a todo aquel que tenga el corazón a la escucha.", EN: "A caring person does not go through life with a convenient blindfold. They also carry in their acquired character the power to stir consciences and bring along all those who have an open heart.", DE: "Ein solidarischer Mensch geht nicht mit einer Augenbinde durchs Leben. Er trägt in seinem erworbenen Wesen auch die Kraft, Gewissen zu bewegen und alle, die ein offenes Herz haben, für das gemeinsame Anliegen zu gewinnen.", FR: "Une personne solidaire ne traverse pas la vie avec un bandeau sur les yeux. Elle porte également dans ses gènes acquis le pouvoir d'éveiller les consciences et d'unir à sa cause tous ceux qui ont le cœur à l'écoute." } as TS,
    sec1p4: { ES: "La sensibilización social ante las numerosas causas que la precisan es el comienzo del cambio. Honestidad y creatividad deben de ir de la mano para atraer la atención de la comunidad. La clave para el éxito es nuestro ejemplo. Que nadie pueda poner nunca en duda que lo que hacemos es por los demás. Que no solo seamos honrados sino que también lo evidenciemos, justificando hasta el último céntimo de nuestras acciones recaudatorias.", EN: "Social awareness of the many causes that need it is the beginning of change. Honesty and creativity must go hand in hand to attract the community's attention. The key to success is our example. May no one ever doubt that what we do is for others. May we not only be honest, but also show it — by accounting for every last cent of our fundraising efforts.", DE: "Die gesellschaftliche Sensibilisierung für die zahlreichen Anliegen, die ihrer bedürfen, ist der Anfang des Wandels. Ehrlichkeit und Kreativität müssen Hand in Hand gehen, um die Aufmerksamkeit der Gemeinschaft zu gewinnen. Der Schlüssel zum Erfolg ist unser Beispiel. Möge niemand je bezweifeln, dass das, was wir tun, für andere geschieht. Mögen wir nicht nur ehrlich sein, sondern es auch zeigen – indem wir jeden letzten Cent unserer Spendenaktionen rechenschaftspflichtig machen.", FR: "La sensibilisation sociale aux nombreuses causes qui en ont besoin est le début du changement. L'honnêteté et la créativité doivent aller de pair pour attirer l'attention de la communauté. La clé du succès est notre exemple. Que personne ne puisse jamais douter que ce que nous faisons est pour les autres. Que nous soyons non seulement honnêtes, mais que nous le montrions aussi, en justifiant jusqu'au dernier centime de nos actions de collecte." } as TS,
    sec1quote: { ES: "No sabíamos lo que éramos capaces de hacer hasta que nos pusimos a hacerlo.", EN: "We didn't know what we were capable of until we set out to do it.", DE: "Wir wussten nicht, wozu wir fähig waren, bis wir es angepackt haben.", FR: "Nous ne savions pas ce dont nous étions capables jusqu'au jour où nous avons commencé." } as TS,
    sec1quotecaption: { ES: "Ese es nuestro lema.", EN: "That is our motto.", DE: "Das ist unser Motto.", FR: "C'est notre devise." } as TS,
    sec2title: { ES: "Todos a Una", EN: "All as One", DE: "Alle gemeinsam", FR: "Tous Ensemble" } as TS,
    sec2desc: { ES: "Colaboramos con muchísimas entidades que merecen nuestra ayuda. Lo hacemos con ilusión y con creatividad. Estos son algunos ejemplos.", EN: "We collaborate with many organisations that deserve our help. We do it with enthusiasm and creativity. Here are some examples.", DE: "Wir arbeiten mit vielen Organisationen zusammen, die unsere Hilfe verdienen. Wir tun es mit Begeisterung und Kreativität. Hier sind einige Beispiele.", FR: "Nous collaborons avec de nombreuses organisations qui méritent notre aide. Nous le faisons avec enthousiasme et créativité. Voici quelques exemples." } as TS,
    sec3title: { ES: "África en el Corazón", EN: "Africa in our Hearts", DE: "Afrika in unserem Herzen", FR: "L'Afrique dans le Cœur" } as TS,
    sec3p1: { ES: "Los Alumnos Solidarios trabajamos desde hace años con diferentes entidades y personas de confianza, impulsores de mejoras locales en la sanidad y la educación.", EN: "Alumnos Solidarios has worked for years with different trusted organisations and individuals who drive local improvements in health and education.", DE: "Wir, die Alumnos Solidarios, arbeiten seit Jahren mit verschiedenen vertrauenswürdigen Organisationen und Personen zusammen, die lokale Verbesserungen in den Bereichen Gesundheit und Bildung vorantreiben.", FR: "Les Alumnos Solidarios travaillent depuis des années avec différentes organisations et personnes de confiance, moteurs d'améliorations locales dans la santé et l'éducation." } as TS,
    sec3p2: { ES: "Comenzamos colaborando con la Fundacion Jigi Seme, 'Sostener la Esperanza', una entidad española centrada en colaborar con el sacerdote burkinabe Eugenio Kabore.", EN: "We started by working with the Jigi Seme Foundation, 'Sustaining Hope', a Spanish organisation focused on supporting the Burkinabe priest Eugenio Kabore.", DE: "Wir begannen mit der Zusammenarbeit mit der Jigi Seme Stiftung, 'Die Hoffnung tragen', einer spanischen Organisation, die sich auf die Unterstützung des burkinischen Priesters Eugenio Kabore konzentriert.", FR: "Nous avons commencé à collaborer avec la Fondation Jigi Seme, 'Soutenir l'Espoir', une organisation espagnole centrée sur le soutien au prêtre burkinabé Eugenio Kabore." } as TS,
    sec3p3: { ES: "Le conocimos personalmente en el Joyfe, cuando vino a dar una charla sobre sus proyectos. Nos comprometimos a ayudarle en lo que pudiéramos. Por ejemplo, colaboramos con el envío de un contenedor que transportaba materiales ginecológicos y oftalmológicos, también informáticos, juguetes, bicicletas y muchísimos libros.", EN: "We met him personally at Joyfe, when he came to give a talk about his projects. We committed to helping him in any way we could. For example, we collaborated on sending a container carrying gynaecological and ophthalmological materials, as well as computers, toys, bicycles and many books.", DE: "Wir haben ihn persönlich im Joyfe kennengelernt, als er einen Vortrag über seine Projekte hielt. Wir verpflichteten uns, ihm so gut wir konnten zu helfen. Zum Beispiel arbeiteten wir beim Versand eines Containers mit, der gynäkologisches und ophthalmologisches Material, Computer, Spielzeug, Fahrräder und viele Bücher transportierte.", FR: "Nous l'avons rencontré personnellement au Joyfe, quand il est venu donner une conférence sur ses projets. Nous nous sommes engagés à l'aider dans la mesure de nos possibilités. Par exemple, nous avons collaboré à l'envoi d'un conteneur transportant du matériel gynécologique et ophtalmologique, ainsi que des ordinateurs, des jouets, des vélos et de nombreux livres." } as TS,
    sec3p4: { ES: "La familia de Guillermo y Nines, cuyos hijos fueron a nuestro colegio, se desplazaron hasta allí y contribuyeron pintando las instalaciones del colegio en Bobo Dioulasso.", EN: "The family of Guillermo and Nines, whose children attended our school, travelled there and contributed by painting the school facilities in Bobo Dioulasso.", DE: "Die Familie von Guillermo und Nines, deren Kinder unsere Schule besuchten, reiste dorthin und leistete ihren Beitrag, indem sie die Schulgebäude in Bobo Dioulasso strich.", FR: "La famille de Guillermo et Nines, dont les enfants fréquentaient notre école, s'est rendue sur place et a contribué en peignant les installations de l'école à Bobo Dioulasso." } as TS,
    sec3p5: { ES: "También enviamos una máquina de soldadura y hasta una ambulancia. Porque el padre Eugenio consiguió levantar un hospital en esa misma ciudad que actualmente ha sido reconocido como uno de los mejores del país.", EN: "We also sent a welding machine and even an ambulance — because Father Eugenio managed to build a hospital in that same city, now recognised as one of the best in the country.", DE: "Wir schickten auch eine Schweißmaschine und sogar einen Krankenwagen. Denn Pater Eugenio schaffte es, in derselben Stadt ein Krankenhaus zu errichten, das heute als eines der besten des Landes anerkannt ist.", FR: "Nous avons également envoyé une machine à souder et même une ambulance. Car le père Eugenio a réussi à construire un hôpital dans cette même ville, aujourd'hui reconnu comme l'un des meilleurs du pays." } as TS,
    sec3block1title: { ES: "Costa de Marfil — Las Hermanitas de la Anunciación", EN: "Ivory Coast — The Little Sisters of the Annunciation", DE: "Elfenbeinküste — Die Kleinen Schwestern der Verkündigung", FR: "Côte d'Ivoire — Les Petites Sœurs de l'Annonciation" } as TS,
    sec3block1p: { ES: "En el país vecino, Costa de Marfil, apoyamos desde hace muchos años a las Hermanitas de la Anunciación. Comenzamos a hacerlo a través de la Fundacion Juan José Márquez, una entidad médica fundada por el doctor Juan José Márquez, otro gran amigo.", EN: "In the neighbouring country, Ivory Coast, we have supported the Little Sisters of the Annunciation for many years. We started doing so through the Juan José Márquez Foundation, a medical organisation founded by Dr Juan José Márquez, another great friend.", DE: "Im Nachbarland Elfenbeinküste unterstützen wir seit vielen Jahren die Kleinen Schwestern der Verkündigung. Wir begannen dies über die Juan José Márquez Stiftung, eine medizinische Organisation, die von Dr. Juan José Márquez, einem weiteren großen Freund, gegründet wurde.", FR: "Dans le pays voisin, la Côte d'Ivoire, nous soutenons depuis de nombreuses années les Petites Sœurs de l'Annonciation. Nous avons commencé à le faire par l'intermédiaire de la Fondation Juan José Márquez, une organisation médicale fondée par le docteur Juan José Márquez, un autre grand ami." } as TS,
    sec3p6: { ES: "Allí los proyectos se dividen en dos áreas. Uno, en el norte, en el dispensario médico que las Hermanitas tienen cerca de la ciudad de Koni, muy cerquita de la frontera con Burkina. Les apoyamos con el suministro de la merienda a los niños del colegio local, más de seiscientos niños que durante años han recibido un vaso de leche a la salida de la escuela. El impulsor de todas estas iniciativas ha sido el doctor Márquez, quien ha dedicado durante años sus vacaciones a asistir a pacientes en estas regiones remotas.", EN: "The projects there are divided into two areas. One is in the north, at the medical dispensary the Little Sisters have near the city of Koni, very close to the border with Burkina Faso. We supported them by providing an afternoon snack to the local schoolchildren — more than six hundred children who for years received a glass of milk after school. The driving force behind all these initiatives has been Dr Márquez, who for years has spent his holidays treating patients in these remote regions.", DE: "Die dortigen Projekte teilen sich in zwei Bereiche auf. Einer davon liegt im Norden, im medizinischen Dispensarium, das die Kleinen Schwestern in der Nähe der Stadt Koni haben, ganz nah an der Grenze zu Burkina Faso. Wir haben sie unterstützt, indem wir die Kinder der örtlichen Schule mit einem Nachmittagssnack versorgten – mehr als sechshundert Kinder, die jahrelang nach der Schule ein Glas Milch bekamen. Der Antrieb für all diese Initiativen war Dr. Márquez, der jahrelang seinen Urlaub damit verbrachte, Patienten in diesen abgelegenen Regionen zu behandeln.", FR: "Les projets y sont divisés en deux zones. L'une est dans le nord, au dispensaire médical que les Petites Sœurs tiennent près de la ville de Koni, tout près de la frontière avec le Burkina Faso. Nous les avons soutenus en fournissant un goûter aux enfants de l'école locale — plus de six cents enfants qui ont reçu pendant des années un verre de lait à la sortie de l'école. Le moteur de toutes ces initiatives a été le docteur Márquez, qui a consacré ses vacances pendant des années à soigner des patients dans ces régions éloignées." } as TS,
    sec3p7: { ES: "En este dispensario, al que también llevan años apoyando los alumnos solidarios del Joyfe, hemos contribuido con la compra de equipamiento médico. También hemos financiado un centro de desnutridos, que atiende a los niños más vulnerables de la región.", EN: "At this dispensary, also long supported by Joyfe's solidarity students, we have contributed to the purchase of medical equipment. We have also funded a malnutrition centre that cares for the most vulnerable children in the region.", DE: "In diesem Dispensarium, das auch seit Jahren von den solidarischen Schülerinnen und Schülern des Joyfe unterstützt wird, haben wir zur Anschaffung von medizinischem Gerät beigetragen. Wir haben auch ein Zentrum für mangelernährte Kinder finanziert, das die verletzlichsten Kinder der Region betreut.", FR: "À ce dispensaire, également soutenu depuis des années par les élèves solidaires du Joyfe, nous avons contribué à l'achat d'équipement médical. Nous avons également financé un centre pour enfants malnutris, qui prend en charge les enfants les plus vulnérables de la région." } as TS,
    sec3block2title: { ES: "📖 Cuentos Contra el Hambre", EN: "📖 Stories Against Hunger", DE: "📖 Geschichten gegen den Hunger", FR: "📖 Histoires Contre la Faim" } as TS,
    sec3block2p: { ES: "Un proyecto muy especial fue la edición de un libro ilustrado de cuentos, que conseguimos gracias a la colaboración de los alumnos y alumnas del JOYFE. 'Cuentos Contra el Hambre' fue un exitazo de ventas, cuya recaudación destinamos al centro de desnutridos.", EN: "A very special project was the publication of an illustrated storybook, made possible thanks to the collaboration of Joyfe students. 'Stories Against Hunger' was a huge sales success, with all proceeds going to the malnutrition centre.", DE: "Ein ganz besonderes Projekt war die Herausgabe eines illustrierten Geschichtenbuchs, das dank der Mitarbeit der Schülerinnen und Schüler des Joyfe möglich wurde. 'Geschichten gegen den Hunger' war ein großer Verkaufserfolg, und der Erlös wurde dem Zentrum für Mangelernäherte zugutekommen.", FR: "Un projet très spécial a été la publication d'un livre illustré de contes, rendu possible grâce à la collaboration des élèves du Joyfe. 'Histoires Contre la Faim' a été un grand succès de vente, dont les recettes ont été destinées au centre pour enfants malnutris." } as TS,
    sec3p8: { ES: "La segunda localización geográfica de los proyectos está en la aldea de Kahankro, a unas tres horas de la capital, Abidjan. Ahí las Hermanitas tienen un colegio, La Anunciación, con más de mil alumnos. Varios alumnos solidarios del JOYFE visitaron sus instalaciones, que han ido ampliándoselas hasta completar la educación Secundaria, gracias a la organización Manos Unidas.", EN: "The second project location is the village of Kahankro, about three hours from the capital, Abidjan. There the Little Sisters have a school, La Anunciación, with over a thousand students. Several Joyfe solidarity students visited the facilities, which have been expanded all the way through secondary education, thanks to the organisation Manos Unidas.", DE: "Der zweite geografische Standort der Projekte ist das Dorf Kahankro, etwa drei Stunden von der Hauptstadt Abidjan entfernt. Dort haben die Kleinen Schwestern eine Schule, La Anunciación, mit mehr als tausend Schülern. Mehrere solidarische Schüler des Joyfe besuchten die Einrichtungen, die dank der Organisation Manos Unidas bis zur Sekundarstufe ausgebaut wurden.", FR: "Le deuxième site géographique des projets est le village de Kahankro, à environ trois heures de la capitale, Abidjan. Là, les Petites Sœurs ont une école, La Anunciación, avec plus de mille élèves. Plusieurs élèves solidaires du Joyfe ont visité les installations, qui ont été agrandies jusqu'à inclure le secondaire, grâce à l'organisation Manos Unidas." } as TS,
    sec3p9: { ES: "En esta escuela tenemos apadrinados como grupo Solidario a cinco niños. En total, coordinamos el apadrinamiento de más de un centenar de estudiantes y estamos muy orgullosos de sus resultados escolares.", EN: "At this school we sponsor, as a Solidarity group, five children. In total, we coordinate the sponsorship of over a hundred students and are very proud of their academic results.", DE: "An dieser Schule haben wir als Solidaritätsgruppe fünf Kinder als Paten. Insgesamt koordinieren wir die Patenschaft für mehr als hundert Schülerinnen und Schüler und sind sehr stolz auf ihre schulischen Leistungen.", FR: "Dans cette école, nous parrainons en tant que groupe Solidaire cinq enfants. Au total, nous coordonnons le parrainage de plus d'une centaine d'élèves et sommes très fiers de leurs résultats scolaires." } as TS,
    sec3p10: { ES: "También desde hace años recibimos la visita anual de profesores y profesoras de la Escuela de la Anunciación, que mejoran su formación en nuestro Colegio.", EN: "We have also welcomed for many years the annual visit of teachers from the Annunciation School, who enhance their training at our school.", DE: "Seit Jahren empfangen wir auch jährlich Lehrerinnen und Lehrer der Schule der Verkündigung, die ihre Ausbildung an unserer Schule vervollständigen.", FR: "Depuis des années, nous accueillons également chaque année des enseignants de l'École de l'Annonciation, qui améliorent leur formation dans notre école." } as TS,
    sec3p11: { ES: "Nosotros hemos apoyado estos proyectos colaborando en los certámenes 'Arte por África', organizados en diferentes centros comerciales de Madrid. El propósito era contribuir con nuestras actividades a impulsar la recaudación del dinero destinado a proyectos en la escuela y en la clínica.", EN: "We have supported these projects by participating in the 'Art for Africa' competitions, organised in various shopping centres in Madrid. The aim was to contribute through our activities to raising funds for the school and clinic projects.", DE: "Wir haben diese Projekte unterstützt, indem wir an den Wettbewerben 'Kunst für Afrika' mitgemacht haben, die in verschiedenen Einkaufszentren in Madrid organisiert wurden. Ziel war es, durch unsere Aktivitäten zur Beschaffung von Mitteln für Projekte in der Schule und der Klinik beizutragen.", FR: "Nous avons soutenu ces projets en participant aux concours 'Art pour l'Afrique', organisés dans différents centres commerciaux de Madrid. L'objectif était de contribuer avec nos activités à la collecte de fonds destinés aux projets de l'école et de la clinique." } as TS,
    sec3p12: { ES: "Podéis haceros una idea de lo que hicimos viendo estas imágenes.", EN: "You can get an idea of what we did from these images.", DE: "Ihr könnt euch anhand dieser Bilder eine Vorstellung davon machen, was wir getan haben.", FR: "Vous pouvez vous faire une idée de ce que nous avons fait en regardant ces images." } as TS,
  },
  sponsorship: {
    pageTitle:   { ES: "Apadrinamiento",            EN: "Sponsorship",             DE: "Patenschaft",                   FR: "Parrainage" } as TS,
    pageDesc:    { ES: "Crea un vínculo único y transforma el futuro de un niño.", EN: "Create a unique bond and transform a child's future.", DE: "Schaffe ein einzigartiges Band und transformiere die Zukunft eines Kindes.", FR: "Créez un lien unique et transformez l'avenir d'un enfant." } as TS,
    what:        { ES: "¿Qué significa apadrinar?", EN: "What does sponsorship mean?", DE: "Was bedeutet Patenschaft?",  FR: "Que signifie parrainer ?" } as TS,
    whatDesc:    { ES: "Apadrinar es mucho más que una aportación económica. Es crear un lazo afectivo y solidario que permite a un niño acceder a educación, salud y nutrición adecuada. Tu apoyo no solo ayuda al niño, sino que impacta positivamente en toda su comunidad.", EN: "Sponsorship is much more than a financial contribution. It creates an affective and solidarity bond that allows a child to access education, health and adequate nutrition. Your support not only helps the child but positively impacts their entire community.", DE: "Eine Patenschaft ist viel mehr als eine finanzielle Beteiligung. Sie schafft ein affektives Band, das einem Kind Zugang zu Bildung, Gesundheit und Ernährung ermöglicht. Deine Unterstützung hilft nicht nur dem Kind, sondern der ganzen Gemeinschaft.", FR: "Le parrainage est bien plus qu'une contribution financière. Il crée un lien affectif et solidaire permettant à un enfant d'accéder à l'éducation, la santé et une alimentation adéquate. Votre soutien profite à toute sa communauté." } as TS,
    includes:    { ES: "Tu aportación incluye:",   EN: "Your contribution includes:", DE: "Dein Beitrag beinhaltet:",    FR: "Votre contribution comprend :" } as TS,
    item1:       { ES: "Material escolar y apoyo educativo.", EN: "School supplies and educational support.", DE: "Schulmaterial und Bildungsunterstützung.", FR: "Fournitures scolaires et soutien éducatif." } as TS,
    item2:       { ES: "Revisiones médicas periódicas.", EN: "Regular medical check-ups.", DE: "Regelmäßige Arztuntersuchungen.", FR: "Bilans médicaux réguliers." } as TS,
    item3:       { ES: "Apoyo nutricional.",        EN: "Nutritional support.",        DE: "Ernährungsunterstützung.",       FR: "Soutien nutritionnel." } as TS,
    item4:       { ES: "Actividades recreativas y de integración.", EN: "Recreational and integration activities.", DE: "Freizeit- und Integrationsaktivitäten.", FR: "Activités récréatives et d'intégration." } as TS,
    cta:         { ES: "Quiero apadrinar ahora",   EN: "I want to sponsor now",       DE: "Jetzt Pate werden",              FR: "Je veux parrainer maintenant" } as TS,
    loginRequired:{ ES: "Inicia sesión para continuar", EN: "Sign in to continue",    DE: "Anmelden um fortzufahren",       FR: "Connectez-vous pour continuer" } as TS,
    loginRequiredDesc:{ ES: "Debes tener una cuenta para enviar una solicitud de apadrinamiento.", EN: "You must have an account to submit a sponsorship request.", DE: "Du musst ein Konto haben, um eine Patenschaftsanfrage zu stellen.", FR: "Vous devez avoir un compte pour soumettre une demande de parrainage." } as TS,
    goToLogin:   { ES: "Ir a iniciar sesión",      EN: "Go to sign in",               DE: "Zum Anmelden",                   FR: "Aller se connecter" } as TS,
    formTitle:   { ES: "Formulario de Apadrinamiento", EN: "Sponsorship Form",        DE: "Patenschaftsformular",           FR: "Formulaire de Parrainage" } as TS,
    formDesc:    { ES: "Responde las preguntas para que podamos ponernos en contacto contigo.", EN: "Answer the questions so we can get in touch with you.", DE: "Beantworte die Fragen, damit wir uns mit dir in Verbindung setzen können.", FR: "Répondez aux questions pour que nous puissions vous contacter." } as TS,
    shareInfo:   { ES: "Al enviar este formulario, aceptas compartir tu información de usuario (nombre y correo electrónico) con el equipo de administración.", EN: "By submitting this form, you agree to share your user information (name and email) with the admin team.", DE: "Durch das Absenden dieses Formulars stimmst du zu, deine Benutzerinformationen (Name und E-Mail) mit dem Admin-Team zu teilen.", FR: "En soumettant ce formulaire, vous acceptez de partager vos informations utilisateur (nom et e-mail) avec l'équipe d'administration." } as TS,
    submit:      { ES: "Enviar solicitud",         EN: "Submit application",          DE: "Bewerbung absenden",             FR: "Soumettre la demande" } as TS,
    submitting:  { ES: "Enviando...",              EN: "Submitting...",               DE: "Senden...",                      FR: "Envoi..." } as TS,
    successTitle:{ ES: "¡Solicitud enviada!",      EN: "Application submitted!",      DE: "Bewerbung gesendet!",            FR: "Demande envoyée !" } as TS,
    successDesc: { ES: "El equipo revisará tu solicitud y se pondrá en contacto contigo pronto.", EN: "The team will review your application and contact you soon.", DE: "Das Team wird deine Bewerbung prüfen und sich bald melden.", FR: "L'équipe examinera votre demande et vous contactera bientôt." } as TS,
    close:       { ES: "Cerrar",                  EN: "Close",                       DE: "Schließen",                      FR: "Fermer" } as TS,
    cancel:      { ES: "Cancelar",                EN: "Cancel",                      DE: "Abbrechen",                      FR: "Annuler" } as TS,
    yourInfo:    { ES: "Tu información de usuario:", EN: "Your user information:",    DE: "Deine Benutzerinformationen:",   FR: "Vos informations utilisateur :" } as TS,
    noFields:    { ES: "El equipo configurará pronto el formulario. Vuelve a intentarlo más tarde.", EN: "The team will configure the form soon. Please try again later.", DE: "Das Team konfiguriert das Formular bald. Bitte versuche es später erneut.", FR: "L'équipe configurera bientôt le formulaire. Veuillez réessayer plus tard." } as TS,
    requiredField:{ ES: "Este campo es obligatorio", EN: "This field is required",   DE: "Dieses Feld ist erforderlich",   FR: "Ce champ est obligatoire" } as TS,
  },
};

export function t(ts: TS, lang: Lang): string {
  return ts[lang] || ts.ES || "";
}

export function useT() {
  const { lang } = useLanguage();
  return (ts: TS) => t(ts, lang);
}
